#!/bin/bash -l
#PBS -l nodes=1:ppn=2
#PBS -l walltime=24:00:00
#PBS -l pmem=60gb
#PBS -A default_project
#PBS -m ae -M vasileios.lemonidis@student.kuleuven.be

module purge
module load matlab/R2019a

cd $VSC_HOME/imagen/deployed

#ENV TO SET:(DEFAULTS)
############
#DATA_ROOT: the directory of the DATA (../SAMPLE_DATA/)
#DATASET_INDEX: dataset to use, 1 or 2 (1)
#RESULTS_ROOT: the directory of the results (../results/)
#THREADS: Number of threads to use (max set by local)
#CHROMOSOME: Chomosome to analyze (1:22)
#BLOCK_SIZE: Block Size for CCA (2000 when MEDIAN_IMPUTE is on else 20000)
#MEDIAN_IMPUTE: Whether to perform median imputation (very fast) or not (very slow) (0)
#PHENO_PATH: Whether to use a specific path for the mat file of the phenotype (defaults to the path where hierarchical clustering algorithm places it)
############

export DATA_ROOT=$VSC_DATA/Thesis/SAMPLE_DATA/
export DATASET_INDEX=2
export RESULTS_ROOT=$VSC_DATA/Thesis/results/
export SCRATCH_ROOT=$VSC_SCRATCH/Thesis/
export CHROMOSOME=${PBS_ARRAYID}

# use temporary directory (not $HOME) for (mostly useless) MATLAB log files
# subdir in $TMPDIR (if defined, or /tmp otherwise)
export MATLAB_LOG_DIR=$(mktemp -d -p ${TMPDIR:-/tmp})

# configure MATLAB Compiler Runtime cache location & size (1GB)
# use a temporary directory in /dev/shm (i.e. in memory) for performance reasons
export MCR_CACHE_ROOT=$(mktemp -d -p /dev/shm)
export MCR_CACHE_SIZE=1024MB

installation="$(dirname $(dirname $(which matlab)))"
./run_demoBrainAsymmetryGenome.sh $installation > genome${PBS_ARRAYID}.log
