#!/bin/bash -l
#PBS -l nodes=1:ppn=1
#PBS -l walltime=00:30:00
#PBS -l pmem=70gb
#PBS -a default_project

module purge
module load matlab/R2019a

cd deployed

export DATA_ROOT=$VSC_DATA/Thesis/SAMPLE_DATA
export DATASET_INDEX=2
export RESULTS_ROOT=$VSC_DATA/Thesis/results
export SCRATCH_ROOT=$VSC_SCRATCH/Thesis
installation="$(dirname $(dirname $(which matlab)))"
./usr/local/micapollo01/MIC/DATA/STUDENTS/vlemon0/code.bak/deployed/run_demoBrainAsymmetryHierarchicalClustering.sh $installation

