#!/bin/bash -l
#PBS -l nodes=1:ppn=1
#PBS -l walltime=00:30:00
#PBS -l pmem=70gb
#PBS -A default_project

module purge
module load matlab

cd $VSC_HOME/imagen/deployed

export DATA_ROOT=$VSC_DATA/Thesis/SAMPLE_DATA
export DATASET_INDEX=2
export RESULTS_ROOT=$VSC_DATA/Thesis/results
export SCRATCH_ROOT=$VSC_SCRATCH/Thesis
installation="$(dirname $(dirname $(which matlab)))"
./run_demoBrainAsymmetryHierarchicalClustering.sh $installation > hierarchical.log

