#!/bin/bash -l
#PBS -l nodes=1:ppn=4
#PBS -l walltime=00:30:00
#PBS -l pmem=20gb
#PBS -A default_project
#PBS -m abe -M vasileios.lemonidis@student.kuleuven.be

module purge
module load matlab/R2019a

cd $VSC_HOME/imagen/deployed

export DATA_ROOT=$VSC_DATA/Thesis/SAMPLE_DATA/
export DATASET_INDEX=2
export RESULTS_ROOT=$VSC_DATA/Thesis/results/
export SCRATCH_ROOT=$VSC_SCRATCH/Thesis/
export THREADS=4
installation="$(dirname $(dirname $(which matlab)))"
./run_demoBrainAsymmetryHierarchicalClustering.sh $installation > hierarchical.log

