#!/bin/bash -l
#PBS -l nodes=1:ppn=2
#PBS -l walltime=6:00:00
#PBS -l pmem=30gb
#PBS -A default_project

module purge 
module load matlab/R2019a

cd $VSC_HOME/imagen/deployed

export DATA_ROOT=$VSC_DATA/Thesis/SAMPLE_DATA/
export DATASET_INDEX=2
export RESULTS_ROOT=$VSC_DATA/Thesis/results/
export SCRATCH_ROOT=$VSC_SCRATCH/Thesis/
export CHROMOSOME=${PBS_ARRAYID}
export THREADS=2
installation="$(dirname $(dirname $(which matlab)))"
./run_demoBrainAsymmetryGenome.sh $installation > genome${PBS_ARRAYID}.log