function GUI(obj,panel)
   if nargin < 2
          handles.panel = figure('Tag', 'Scan3DFig', ...
                                'Units', 'characters', ...
                                'Position', [129.6000    2.9231  90   25], ...
                                'Name', obj.Type, ...
                                'MenuBar', 'none', ...
                                'NumberTitle', 'off', ...
                                'Color', get(0,'DefaultUicontrolBackgroundColor'), ...
                                'Resize', 'on',...
                                'CloseRequestFcn',@my_close_Callback);
   else
       handles.panel = panel;
   end
   guidata(handles.panel,handles);
   obj.gui = handles;
end
%% CallBacks
function my_close_Callback(hObject,evendata)
         handles = guidata(hObject);
         delete(handles.panel);        
end