classdef TableGUI < superClass
   % GUI PROPERTIES
   properties
      Version = 'Version 1, 2015'; 
   end
   properties (Hidden = true)
      Figure = [];
      BFView = [];
      PFView = [];
      NDView = [];
      ARView = [];
      Status = 'INIT';
      Handles = [];
   end
   properties (Dependent = true, Hidden = true);
   end
   % DATA PROPERTIES
   properties (Hidden = true)
       RefScan = [];
       F1 = [];
       F2 = [];
       FA = [];
       FND = [];
       FAR = [];
       TableData = cell(1,11);
   end
   properties (Dependent = true, Hidden = true)
   end
   methods % Constructor
        function obj = TableGUI(varargin)
            obj = obj@superClass(varargin{:});
            for i=1:1:11
                obj.TableData{i} = num2str(i);
            end
            constructGUI(obj);
        end
   end
   methods % GUI GETTING/SETTING
       function out = get.BFView(obj)
           out = obj.BFView;
           if ~superClass.isH(out), out = []; end
       end
       function out = get.PFView(obj)
           out = obj.PFView;
           if ~superClass.isH(out), out = []; end
       end
       function out = get.NDView(obj)
           out = obj.NDView;
           if ~superClass.isH(out), out = []; end
       end
       function out = get.ARView(obj)
           out = obj.ARView;
           if ~superClass.isH(out), out = []; end
       end
       function obj = set.Status(obj,in)
           obj.Status = in;
           updatePointer(obj,in);
       end
   end
   methods % DATA GETTING/SETTING
       function obj = set.RefScan(obj,in)
           obj.RefScan = in;
           obj.F1 = clone(in);
           obj.F1.ColorMode = 'Single';
           obj.F1.SingleColor = [0.8 0.8 0.8];
           obj.F1.Material = 'Dull';
           obj.F1.ViewMode = 'Wireframe';
           obj.F1.Axes = obj.BFView.RenderAxes;
           obj.F1.Visible = true;
           obj.F2 = clone(in);
           obj.F2.ColorMode = 'Single';
           obj.F2.SingleColor = [0 0.4471 0.7412];
           obj.F2.Material = 'Dull';
           obj.F2.ViewMode = 'Wireframe';
           obj.F2.Axes = obj.BFView.RenderAxes;
           obj.F2.Visible = true;
           obj.FA = clone(in);
           obj.FA.ColorMode = 'Single';
           obj.FA.SingleColor = [0.8 0.8 0.8];
           obj.FA.Material = 'Dull';
           obj.FA.ViewMode = 'Solid';
           obj.FA.Axes = obj.PFView.RenderAxes;
           obj.FA.Visible = true;
           obj.FND = clone(in);
           obj.FND.Value = zeros(1,in.nrV);
           obj.FND.ColorMode = 'Indexed';
           obj.FND.SingleColor = [0.8 0.8 0.8];
           obj.FND.Material = 'Dull';
           obj.FND.ViewMode = 'Solid';
           obj.FND.Axes = obj.NDView.RenderAxes;
           obj.FND.Visible = true;
           obj.FAR = clone(in);
           obj.FAR.Value = zeros(1,in.nrV);
           obj.FAR.ColorMode = 'Indexed';
           obj.FAR.SingleColor = [0.8 0.8 0.8];
           obj.FAR.Material = 'Dull';
           obj.FAR.ViewMode = 'Solid';
           obj.FAR.Axes = obj.ARView.RenderAxes;
           obj.FAR.Visible = true;
       end
   end
   methods % CONSTRUCTION
       function constructGUI(obj)
           constructTableGUI(obj);
           constructViewers(obj);
           obj.Status = 'READY';
       end
       function constructViewers(obj)
           % BF VIEWER
           obj.BFView = viewer3DObj('Visible',false);
           obj.BFView.Figure.Position = [89.2000   50.0000  100.0000   30.0000];
           obj.BFView.Tag = 'BFVIEW';set(obj.BFView.Figure,'CloseRequestFcn', @myCloseFunction);
           obj.BFView.Application = obj;
           obj.BFView.Figure.Name = 'OVERLAY';obj.BFView.Visible = true;
           % PF VIEWER
           obj.PFView = viewer3DObj('Visible',false);
           obj.PFView.Figure.Position = [89.2000   16.5385  100.0000   30.0000];
           obj.PFView.Tag = 'PFVIEW';set(obj.PFView.Figure,'CloseRequestFcn', @myCloseFunction);
           obj.PFView.Application = obj;
           obj.PFView.Figure.Name = 'MORPHING';obj.PFView.Visible = true;
           % ND VIEWER
           obj.NDView = viewer3DObj('Visible',false);
           obj.NDView.Figure.Position = [193.6000   50.1538  100.0000   30.0000];
           obj.NDView.Tag = 'NDVIEW';set(obj.NDView.Figure,'CloseRequestFcn', @myCloseFunction);
           obj.NDView.Application = obj;
           obj.NDView.Figure.Name = 'FEATURE PROMINENCE         INWARD (Blue) <=> OUTWARD (Red)';obj.NDView.Visible = true;
           % AR VIEWER
           obj.ARView = viewer3DObj('Visible',false);
           obj.ARView.Figure.Position = [193.0000   16.5385  100.0000   30.0000];
           obj.ARView.Tag = 'ARVIEW';set(obj.ARView.Figure,'CloseRequestFcn', @myCloseFunction);
           obj.ARView.Application = obj;
           obj.ARView.Figure.Name = 'FEATURE SIZE               SMALLER (Blue) <=> BIGGER (Red)';obj.ARView.Visible = true;
       end
       function constructTableGUI(obj)
            % MAIN FIGURE;
            obj.Figure = figure(...
                                'Units','characters',...
                                'Position',[3.0000   26.7692   82.4000   50],...
                                'Visible',get(0,'defaultfigureVisible'),...
                                'Color',get(0,'defaultfigureColor'),...
                                'CurrentAxesMode','manual',...
                                'IntegerHandle','off',...
                                'MenuBar','none',...
                                'Name','Table GUI                     Copyright (c) 2015 P. Claes',...
                                'NumberTitle','off',...
                                'Resize','off',...
                                'PaperPosition',get(0,'defaultfigurePaperPosition'),...
                                'ScreenPixelsPerInchMode','manual',...
                                'ChildrenMode','manual',...
                                'ParentMode','manual',...
                                'HandleVisibility','callback',...
                                'Tag','figure1',...
                                'CloseRequestFcn',@TableGUICloseCallback);
            setappdata(obj.Figure,'Application',obj);
            obj.Handles.FigStr = uicontrol(...
                                'Parent',obj.Figure,...
                                'FontUnits',get(0,'defaultuicontrolFontUnits'),...
                                'Units','characters',...
                                'String','Peter.Claes@kuleuven.be',...
                                'Style','text',...
                                'Position',[0.8 -0.0769230769230769 28.8 1.76923076923077],...
                                'Children',[],...
                                'ParentMode','manual',...
                                'Tag','text2');
            % MENU ITEMS
            obj.Handles.FileMenu = uimenu(...
                                'Parent',obj.Figure,...
                                'Label','File',...
                                'ChildrenMode','manual',...
                                'ParentMode','manual',...
                                'Tag','Untitled_1');
            obj.Handles.ImportTable = uimenu(...
                                'Parent',obj.Handles.FileMenu,...
                                'Callback',@ImportTableCallback,...
                                'Label','Import Table',...
                                'ParentMode','manual',...
                                'Tag','load');
            setappdata(obj.Handles.ImportTable,'Application',obj);
            % ACTION PANEL
            %[6.8 2.61538461538462 16.6 6.30769230769231]
            obj.Handles.ActionPanel = uipanel(...
                                'Parent',obj.Figure,...
                                'FontUnits',get(0,'defaultuipanelFontUnits'),...
                                'Units','characters',...
                                'Title','ACTIONS',...
                                'Position',[3.6 1.9 36.4 8],...
                                'Visible',get(0,'defaultuipanelVisible'),...
                                'ParentMode','manual',...
                                'Tag','uipanel1');
            obj.Handles.SyncButton = uicontrol(...
                                'Parent',obj.Handles.ActionPanel,...
                                'FontUnits',get(0,'defaultuicontrolFontUnits'),...
                                'Units','characters',...
                                'String','SYNC VIEWERS',...
                                'Style',get(0,'defaultuicontrolStyle'),...
                                'Position',[6 4.5 22.6 1.92307692307692],...
                                'Callback',@SyncButtonCallback,...
                                'Children',[],...
                                'KeyPressFcn',blanks(0),...
                                'ParentMode','manual',...
                                'DeleteFcn',blanks(0),...
                                'ButtonDownFcn',blanks(0),...
                                'Tag','pushbutton2');
            setappdata(obj.Handles.SyncButton,'Application',obj);
            obj.Handles.AFSlider = uicontrol(...
                                'Parent',obj.Handles.ActionPanel,...
                                'FontUnits',get(0,'defaultuicontrolFontUnits'),...
                                'Units','characters',...
                                'Max',5,...
                                'Min',1,...
                                'String',{  'Slider' },...
                                'Style','slider',...
                                'Value',2,...
                                'Position',[1 1 32.4 1.30769230769231],...
                                'BackgroundColor',[0.9 0.9 0.9],...
                                'Callback',@AFSliderCallback,...
                                'Children',[],...
                                'ParentMode','manual',...
                                'Tag','slider1');
            setappdata(obj.Handles.AFSlider,'Application',obj);
            obj.Handles.StrAF = uicontrol(...
                                'Parent',obj.Handles.ActionPanel,...
                                'FontUnits',get(0,'defaultuicontrolFontUnits'),...
                                'Units','characters',...
                                'String','Amplification Factor',...
                                'Style','text',...
                                'Position',[2 2.5 31.8 1.30769230769231],...
                                'Children',[],...
                                'Visible',get(0,'defaultuicontrolVisible'),...
                                'ParentMode','manual',...
                                'Tag','text3');
            % INFORMATION PANEL
            obj.Handles.SettingsPanel = uipanel(...
                                'Parent',obj.Figure,...
                                'FontUnits',get(0,'defaultuipanelFontUnits'),...
                                'Units','characters',...
                                'Title','INFORMATION',...
                                'Position',[1 10 80 40],...
                                'Visible',get(0,'defaultuipanelVisible'),...
                                'ResizeFcn',blanks(0),...
                                'ParentMode','manual',...
                                'DeleteFcn',blanks(0),...
                                'ButtonDownFcn',blanks(0),...
                                'Tag','uipanel3');
            obj.Handles.Table = uitable(...
                                        'Parent',obj.Handles.SettingsPanel,...
                                        'Data',obj.TableData,...
                                        'Tag','table');
            setappdata(obj.Handles.Table,'Application',obj);
            % VISUALIZATION PANEL
            obj.Handles.ViewerPanel = uipanel(...
                                'Parent',obj.Figure,...
                                'FontUnits',get(0,'defaultuipanelFontUnits'),...
                                'Units','characters',...
                                'Title','VIEWERS',...
                                'Position',[40 1.9 40 8],...
                                'Visible',get(0,'defaultuipanelVisible'),...
                                'ResizeFcn',blanks(0),...
                                'ParentMode','manual',...
                                'DeleteFcn',blanks(0),...
                                'ButtonDownFcn',blanks(0),...
                                'Tag','uipanel4');
            obj.Handles.BFBox = uicontrol(...
                                'Parent',obj.Handles.ViewerPanel,...
                                'FontUnits',get(0,'defaultuicontrolFontUnits'),...
                                'Units','characters',...
                                'String','Overlay',...
                                'Style','checkbox',...
                                'Value',1,...
                                'Position',[3 3.84615384615385 13.2 1.76923076923077],...
                                'Callback',@BFBoxCallback,...
                                'Children',[],...
                                'ParentMode','manual',...
                                'Tag','BV');
            setappdata(obj.Handles.BFBox,'Application',obj);                
            obj.Handles.PFBox = uicontrol(...
                                'Parent',obj.Handles.ViewerPanel,...
                                'FontUnits',get(0,'defaultuicontrolFontUnits'),...
                                'Units','characters',...
                                'String','Morph',...
                                'Style','checkbox',...
                                'Value',1,...
                                'Position',[3 1.23076923076923 16.8 1.76923076923077],...
                                'Callback',@PFBoxCallback,...
                                'Children',[],...
                                'ParentMode','manual',...
                                'Tag','PV');
            setappdata(obj.Handles.PFBox,'Application',obj);
            obj.Handles.NDBox = uicontrol(...
                                'Parent',obj.Handles.ViewerPanel,...
                                'FontUnits',get(0,'defaultuicontrolFontUnits'),...
                                'Units','characters',...
                                'String','Feature Prom.',...
                                'Style','checkbox',...
                                'Value',1,...
                                'Position',[21.6 3.76923076923077 26.2 1.76923076923077],...
                                'Callback',@NDBoxCallback,...
                                'Children',[],...
                                'ParentMode','manual',...
                                'Tag','NV');
            setappdata(obj.Handles.NDBox,'Application',obj);
            obj.Handles.ARBox = uicontrol(...
                                'Parent',obj.Handles.ViewerPanel,...
                                'FontUnits',get(0,'defaultuicontrolFontUnits'),...
                                'Units','characters',...
                                'String','Feature Size',...
                                'Style','checkbox',...
                                'Value',1,...
                                'Position',[21.6 1.23076923076923 26.2 1.76923076923077],...
                                'Callback',@ARBoxCallback,...
                                'Children',[],...
                                'ParentMode','manual',...
                                'Tag','NV');
            setappdata(obj.Handles.ARBox,'Application',obj);
       end
       function updatePointer(obj,in)
           if isempty(obj.Figure), return; end
           switch in
               case 'BUSY'
                   set(obj.Figure,'Pointer','watch');
                   set(obj.BFView.Figure,'Pointer','watch');
                   set(obj.PFView.Figure,'Pointer','watch');
                   set(obj.NDView.Figure,'Pointer','watch');
                   set(obj.ARView.Figure,'Pointer','watch');
               case 'READY'
                   set(obj.Figure,'Pointer','arrow');
                   set(obj.BFView.Figure,'Pointer','arrow');
                   set(obj.PFView.Figure,'Pointer','arrow');
                   set(obj.NDView.Figure,'Pointer','arrow');
                   set(obj.ARView.Figure,'Pointer','arrow');
               case 'INIT'
                   set(obj.Figure,'Pointer','watch');
               otherwise
           end
           drawnow;
       end
   end
   methods % DESTRUCTION
       function delete(obj)
                try 
                   delete(obj.Figure);
                catch 
                end
                if ~isempty(obj.BFView), delete(obj.BFView); end
                if ~isempty(obj.PFView), delete(obj.PFView); end
                if ~isempty(obj.NDView), delete(obj.NDView); end
                if ~isempty(obj.ARView), delete(obj.ARView); end
                delete@superClass(obj);
       end
   end
end % classdef
%% 3D VIEWER CALLBACKS
function myCloseFunction(hObject,eventdata)
         viewer = get(hObject,'UserData');
         obj = viewer.Application;
         switch viewer.Tag
             case 'BFVIEW'
                 obj.Handles.BFBox.Value = 0;
             case 'PFVIEW'
                 obj.Handles.PFBox.Value = 0;
             case 'NDVIEW'
                 obj.Handles.NDBox.Value = 0;
             case 'ARVIEW'
                 obj.Handles.ARBox.Value = 0;
         end         
         viewer.Visible = false;
end
%% GENERAL CALLBACKS
function TableGUICloseCallback(hObject,eventdata) %#ok<*INUSD>
         obj = getappdata(hObject,'Application');
         obj.Status = 'BUSY';
         delete(obj);
         close all;
end
%% MENU CALLBACKS
function ImportTableCallback(hObject,eventdata)
         obj = getappdata(hObject,'Application');
         obj.Handles.StrProgress.String = 'SELECT Table FILE';
         [filename, pathname] = uigetfile({'*.mat','PREDICTION MODEL'},'MultiSelect','off');
         if filename == 0, obj.Handles.StrProgress.String = 'IMPORT CANCELLED'; return; end
         obj.Status = 'BUSY';
         cd(pathname);
         drawnow;
         in = load(filename);
         obj.Status = 'READY';
end
%% ACTION CALLBACKS
function SyncButtonCallback(hObject,eventdata)
         obj = getappdata(hObject,'Application');
         if isempty(obj.BFView), return; end
         if ~isempty(obj.PFView), syncCamera(obj.BFView,obj.PFView); obj.PFView.SceneLightPosition = obj.BFView.SceneLightPosition; end
         if ~isempty(obj.NDView), syncCamera(obj.BFView,obj.NDView); obj.NDView.SceneLightPosition = obj.BFView.SceneLightPosition; end
         if ~isempty(obj.ARView), syncCamera(obj.BFView,obj.ARView); obj.ARView.SceneLightPosition = obj.BFView.SceneLightPosition; end
end
function AFSliderCallback(hObject,eventdata)
         obj = getappdata(hObject,'Application');
%          if isempty(obj.Subject.BaseFace), return; end
%          if isempty(obj.Subject.PredFace), return; end
%          if isempty(obj.Subject.AmplFace), return; end
%          dir = obj.Subject.PredFace.Vertices-obj.Subject.BaseFace.Vertices;
%          obj.Subject.AmplFace.Vertices = obj.Subject.BaseFace.Vertices + obj.Handles.AFSlider.Value*dir;
end
%% VIEWER CALLBACKS
function BFBoxCallback(hObject,eventdata)
         obj = getappdata(hObject,'Application');
         obj.BFView.Visible = get(hObject,'Value');
end
function PFBoxCallback(hObject,eventdata)
         obj = getappdata(hObject,'Application');
         obj.PFView.Visible = get(hObject,'Value');
end
function NDBoxCallback(hObject,eventdata)
         obj = getappdata(hObject,'Application');
         obj.NDView.Visible = get(hObject,'Value');
end
function ARBoxCallback(hObject,eventdata)
         obj = getappdata(hObject,'Application');
         obj.ARView.Visible = get(hObject,'Value');
end
%% LICENSE CALLBACKS