function constructAssessmentTool(obj)
% GENERATING THE MAIN FIGURE PANEL
%#function arrayviewfunc workspacefunc
  obj.Handles.Panel = figure('Tag', 'Panel', ...
                             'Units', 'characters', ...
                             'Position', [107.4000   25.6154  153.6000   47.5385], ...
                             'Name',obj.Tag, ...
                             'MenuBar', 'none', ...
                             'NumberTitle', 'off', ...
                             'Color', get(0,'DefaultUicontrolBackgroundColor'), ...
                             'Resize', 'on',...
                             'CloseRequestFcn',@PanelCloseCallback);
   setappdata(obj.Handles.Panel,'Application',obj);                      
% GENERATING THE PANELS
constructAssessmentPanel(obj);
constructVisualizationPanel(obj);
constructSettingsPanel(obj);
constructActionsPanel(obj);
end

%% MAIN PANEL CALLBACKS
function PanelCloseCallback(hObject,eventdata)
         obj = getappdata(hObject,'Application');
         delete(obj);
         close all;
end
